# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    # Look for `build.gradle` files in the `root` directory
    directory: "/"
    # The branch to create the Pull Request to
    target-branch: "main"
    # Check the registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "23:00"
