version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  backend:
    image: my-pp
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: example
    depends_on:
      - db
    ports:
      - 8080:8080
