name: Auto pull request
on:
  pull_request:
    types: [opened]
jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a pull request is made
    steps:
      - name: Send message to Slack API
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} TESTTITLE {status_message}"
          message_format: "{emoji} *{workflow}* MESSAGEFORMAT {status_message} in <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
