name: Auto pull request
on:
  [pull_request]
jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a pull request is made
    steps:
      - name: Send message to Slack API
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} for {commit_url}"
          message_format: "${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.message }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
