name: Auto pull request
on:
  pull_request:
    types: [opened]
jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a pull request is made
    steps:
      - name: Send message to Slack API
        uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{secrets.SLACK_GITHUB_PR}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: C03P685JDU2
          name: 'Test'
          icon_emoji: ':poop:'
