name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # only allow for minor changes to be auto merged
          target: minor
          github-token: ${{ secrets.mytoken }}