name: 'build'

on:
  - workflow_call
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          title: ${{ github.head_ref }}
          branch: ${{ github.head_ref || github.ref }}
          base: main

      - name: Add comment
        run: gh pr comment $PR_URL --body "This pull request was created automatically."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Sends a message to Slack when a pull request is made
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "Auto pull request created for {{ branch }}"
          message_format: "{{ github.event.head_commit.author.name }} {{ github.event.head_commit.message }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
