name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  build:
    uses:
      codecentricnl/declaration-event-service/.github/workflows/build.yml@main
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: 'build/test-result/**/*.xml' # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
