name: 'Test Report'

on:
  - workflow_call

jobs:
  steps:
  - name: Publish Test Report
    uses: mikepenz/action-junit-report@v3
    with:
      report_paths: '**/build/test-results/test/TEST-*.xml'
      detailed_summary: true
