name: 'Test Report'

on:
  - workflow_call

jobs:
  junit-report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Test Report
          path: build/test-results/test/
          fail-on-error: true
          reporter: java-junit
